Add a script to check html validity of emails and webpage using W3C validator
justLiberals/justliberals.org.uk pull request #14
Opened 2021-05-14 14:02 UTC by ultratwo

This pull request adds a `validate.js` script that checks the validity of using the validator at `validator.w3.org`. For each file with errors it places a json summary of the errors in `filename + ".json"`. If any file has errors the script exits with failure. You can ignore specific errors by adding them to `ignored_errors` and `ignored_email_errors` at the top of `validate.js`.

Currently the repository contains large numbers of unignored errors in every file.

2021-05-14 20:09 UTC, JamesBelchamber commented
Okay, this is awesome :ok_hand: unfortunately almost all our documents fail :sweat_smile: can you add all existing errors to the two lists? This isn't _great_ but it'll break the build if any FURTHER invalid HTML/CSS is created.

In addition, can you add `validate` to the `build:*` namespace, so it gets run by the CI as part of the cascade?

2021-05-14 20:12 UTC, JamesBelchamber requested changes
Okay, this is awesome :ok_hand: unfortunately almost all our documents fail :sweat_smile: can you add all existing errors to the two lists? This isn't _great_ but it'll break the build if any FURTHER invalid HTML/CSS is created.

In addition, can you add `validate` to the `build:*` namespace, so it gets run by the CI as part of the cascade?

2021-05-14 20:12 UTC, JamesBelchamber commented on validate.js
> +ignored_email_errors = [
Add all the existing email errors to this list

2021-05-14 20:12 UTC, JamesBelchamber commented on validate.js
> +ignored_errors = [
Add all the existing website errors to this list

2021-05-14 20:12 UTC, JamesBelchamber commented on package.json
> +    "validate": "node validate.js"
Add this to the `build:` namespace (you can add it to the end, on line 29 and bumping that down a line)

2021-05-14 21:54 UTC, ultratwo commented
New commit makes all changes requested by James.

2021-05-15 12:25 UTC, JamesBelchamber approved these changes

2021-05-15 12:26 UTC, merged

2021-05-15 12:26 UTC, JamesBelchamber commented
Cracking stuff :sunglasses: thank you!